version: '3.9'

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3 
  celery:
    build: .
    command: celery -A CONSTRUCTION_BILLING_PRJ worker --loglevel=info  
    env_file:
      - .env  
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
  web:
    build: .
    command: gunicorn CONSTRUCTION_BILLING_PRJ.wsgi:application --bind 0.0.0.0:8000   
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media   
    depends_on:
      - redis
      - celery    
    env_file:
      - .env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf 
      - ./media:/app/media 
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - web     
volumes:  
  redis-data:
  certbot-etc:
    external: true