# Generated by Django 5.1 on 2024-11-09 10:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(default='1', max_length=100)),
                ('bill_number', models.IntegerField(default=1)),
                ('submitted', models.BooleanField(default=False)),
                ('bill_date', models.DateField()),
                ('other_details', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Bill',
            },
        ),
        migrations.CreateModel(
            name='COPMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=50, null=True)),
                ('acno', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_address', models.CharField(blank=True, max_length=800, null=True)),
                ('receiver_gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_state', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_code', models.CharField(blank=True, max_length=50, null=True)),
                ('order_acceptance_no', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_of_payment', models.CharField(blank=True, max_length=250, null=True)),
                ('hsn_sa_code', models.CharField(blank=True, max_length=50, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'COPMaster',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'super_admin'), ('admin', 'admin'), ('project', 'project'), ('company', 'company'), ('consultant', 'consultant')], max_length=30),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('company_address', models.CharField(max_length=500, null=True)),
                ('company_email', models.EmailField(max_length=254, null=True)),
                ('country_code', models.CharField(default='+91', max_length=4)),
                ('company_phone', models.CharField(help_text='Phone number without Country Code', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('other_details', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_address', models.CharField(blank=True, max_length=500, null=True)),
                ('consultant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country_code', models.CharField(default='+91', max_length=4)),
                ('consultant_phone', models.CharField(blank=True, help_text='Phone number without Country Code', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('other_details', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Consultant',
            },
        ),
        migrations.CreateModel(
            name='COP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ugst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('supply_of_goods', models.BooleanField(default=False)),
                ('supply_of_services', models.BooleanField(default=False)),
                ('stock_transfer', models.BooleanField(default=False)),
                ('debit_credit_notes', models.BooleanField(default=False)),
                ('other_supplies', models.BooleanField(default=False)),
                ('gst_inclusive', models.BooleanField(default=False)),
                ('date_of_bill', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bill')),
                ('copmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.copmaster')),
            ],
            options={
                'db_table': 'COP',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=500, null=True)),
                ('client', models.CharField(blank=True, max_length=500, null=True)),
                ('consultant', models.CharField(blank=True, default='self', max_length=500, null=True)),
                ('contractor', models.CharField(blank=True, default='self', max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('other_details', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.AddField(
            model_name='copmaster',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project'),
        ),
        migrations.AddField(
            model_name='bill',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project'),
        ),
        migrations.CreateModel(
            name='WOBOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100000, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('headings', models.CharField(blank=True, max_length=100000, null=True)),
                ('subheading', models.CharField(blank=True, max_length=100000, null=True)),
                ('work_order_date', models.DateField()),
                ('extra_item', models.BooleanField(default=False)),
                ('other_details', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
            ],
            options={
                'db_table': 'WOBOQItem',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_description', models.CharField(blank=True, max_length=500, null=True)),
                ('count', models.IntegerField(default=1, help_text='the number of items with this measurement')),
                ('number', models.IntegerField(default=1, help_text='Extra count field')),
                ('length', models.DecimalField(decimal_places=2, default=1.0, max_digits=15, null=True)),
                ('breadth', models.DecimalField(decimal_places=2, default=1.0, max_digits=15, null=True)),
                ('height', models.DecimalField(decimal_places=2, default=1.0, max_digits=15, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('entry_date', models.DateField()),
                ('other_details', models.CharField(blank=True, max_length=500, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bill')),
                ('woboqitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.woboqitem')),
            ],
            options={
                'db_table': 'Measurement',
            },
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('project', 'bill_name'), name='unique_project_bill'),
        ),
    ]
